### PR TITLE
Login

### PR DESCRIPTION
**Pull request by 609**
This can be merged after this branches this order:
1. Buy Now
2. pinJS
3. Login

### CODE REVIEW

**Comment by Lpember** [comment]
Stan, has conflict.

**Comment by 609** [comment]
Ok, I'll fix it today

**Comment by Lpember** [comment]
Hey Stan, what is the reason that this can not be tested on the development server (http://ec2-52-88-165-27.us-west-2.compute.amazonaws.com)
I assume it is something to do with the configuration of the mail server used to send the emails? But I can't see anywhere a place to change those to test on the development server

**Comment by SixZeroNine** [comment]
Ok, I will investigate and fix it tommorow.

**Comment by 609** [comment]
Ok, I will investigate and fix it tommorow.

**Pull request merged**
