### PR TITLE
Buy button

### PR DESCRIPTION
**Pull request by 609**
Added features module
Created custom feature that contains all rules related to commerce so I can export changes
Created custom rules action
Commented egg_preprocess_html($variables, $hook); since that function does not exsist.
Charity and Payed tour buy button is now leading directly to cart page.

### CODE REVIEW

**Comment by Lpember** [comment]
Paid Tour button does not appear to lead direct to cart page. https://app.asana.com/0/46749327662339/46880237572475

**Comment by 609** [comment]
I wrote update scripts, just run update.php to make everything works.

**Comment by Lpember** [comment]
Thanks Stan, just running script now. I didn't notice it before but features is spelt wrong on one of your modules: /* app/sites/all/modules/custom_fetures/... */

**Comment by Lpember** [comment]
ran the script. Not seeing the update, am I doing something wrong?

**Pull request merged**
