### PR TITLE
Pin js

### PR DESCRIPTION
**Pull request by 609**
This can me merged after buy now branch.

### CODE REVIEW

**Comment by Lpember** [comment]
Git says conflict, even after buy now button branch merge.

**Comment by SixZeroNine** [comment]
I can't replicate at this moment, I'll try to check and resolve tonight

**Comment by Lpember** [comment]
Conflict appears to not be any real issue. Git's just noticing that the egg_master.install has been modified for the miny and advagg module... Seems 100% ok to me. not sure why it picked it up.

**Comment by SixZeroNine** [comment]
I'll check it just in case.

**Comment by Lpember** [comment]
Stan. Should I be able to replicate this fix on local host? Or will it need to be on live site?

**Comment by 609** [comment]
Yes you can replicate it on local. You can check result with google chrome inspector, networking tab.

**Comment by Lpember** [comment]
ah ok checking now

**Comment by Lpember** [comment]
Awesome the normalised css has kept the page very small. Did this fix include sending traffic over the bluehost public ssl?

**Pull request merged**
